---
title: "Radix For Finance"
description: |
  Takingthe `radix` packagefor a test spin for finacial reporting
author:
  - name: Gouthaman Tharmathasan
date: "`r Sys.Date()`"
output: radix::radix_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

# load libraries

```{r, echo=TRUE}
library(tidyverse)
library(tidyquant)
library(timetk)
library(plotly)
library(rmarkdown)
```

# get financial data

```{r, echo=TRUE}
FANG <- c("FB", "AMZN", "NFLX", "GOOG") %>% 
  tq_get(from = "2014-04-01", to = today())
```

# print interactive Table of Monthly Returns

```{r, echo=TRUE}
cummulative_tbl <- FANG %>% 
  mutate(symbol = as_factor(symbol)) %>% 
  group_by(symbol) %>% 
  mutate(returns = adjusted - lag(adjusted)) %>% 
  mutate(returns = replace_na(returns, 0)) %>% 
  mutate(cummulative_returns = cumsum(returns))

cummulative_tbl %>% 
  select(symbol, date, adjusted, cummulative_returns) %>% 
  paged_table()
```

# plot interactive financial chart

```{r, fig.height=5.5}
cummulative_tbl %>% 
  ungroup() %>% 
  plot_time_series(.date_var = date,
                   .value = cummulative_returns,
                   .color_var = symbol,
                   .smooth = FALSE,
                   .title = "FANG Performance",
                   .x_lab = "",
                   .y_lab = "Cummulative Returns")
```

<aside>
FANG Share Price

```{r, fig.height=20}
cummulative_tbl %>% 
  plot_time_series(.date_var = date,
                   .value = adjusted,
                   .color_var = symbol,
                   .legend_show = FALSE,
                   .smooth = FALSE,
                   .line_size = 1,
                   .x_lab = "",
                   .y_lab = "Share Price (Adjusted)",
                   .title = "",
                   .facet_vars = symbol,
                   .facet_scales = "free_y",
                   .interactive = FALSE) +
  scale_y_continuous(labels = scales::dollar)
  
```
<aside>
